### ISSUE TITLE
Bug in GetRealmRoles() method of OAuthRealm class in case of users with multiple roles assigned

### ISSUE THREAD

**Issue by shripadnalgirkar** [seedstack/oauth-addon#18]
Hi Team
This issue comes in case of below conditions 
1. Users has multiple roles assigned 
2. treatScopesAsRoles flag is set to true, 
3. The role has a valorized values in scope {scope}.
`getRealmRoles()==>accessClaimToStrings()` method of OAuthRealm class this method should resolve individual role as a separate string (i.e. "Role1.{scope}" & "Role2.{scope}"), however currently it is being resolved as a combined array string (i.e. "["Role1.{scope}","Role2.{scope}"]" and this is causing issue while doing the regular expression matching in org.seedstack.seed.security.internal.authorization.ConfigurationRoleMapping.resolveRoles() method in cases of {scoped} auth flow.
Could you please resolve this on priority as it is a critical defect and blocking the application?
Please let me know if you see any issues.
Thanks & Regards
Shripad

**Comment by shripadnalgirkar** [comment]
I have created a pull request with the fix for this issue

**Comment by adrienlauer** [comment]
Fixed in v3.2.0
